name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  RENOVATE_VERSION: 43.253.1 # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: 📥 Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          save-cache: true

  commitlint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != github.event.pull_request.head.repo.owner.login }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          show-progress: false
          filter: blob:none # we don't need all blobs, only the full tree

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
        continue-on-error: true

  lint:
    needs:
      - prepare
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != github.event.pull_request.head.repo.owner.login }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: 📥 Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Lint
        run: npm run lint

  lint-actions:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          version: 1.26.1

  e2e:
    needs:
      - prepare
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != github.event.pull_request.head.repo.owner.login }}

    strategy:
      fail-fast: false
      matrix:
        configurationFile:
          - example/renovate-config.js
          - example/renovate-config.json
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: 📥 Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Build
        run: npm run build

      - name: Configure renovate token
        run: |
          if [[ "${RENOVATE_TOKEN}" != ""  ]]; then
            echo "RENOVATE_TOKEN=${RENOVATE_TOKEN}" >> $GITHUB_ENV
          else
            echo "RENOVATE_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}

      - name: Renovate test
        uses: ./
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: ${{ matrix.configurationFile }}

      - name: Renovate test with entrypoint
        uses: ./
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: ${{ matrix.configurationFile }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
          docker-cmd-file: example/entrypoint.sh
          docker-user: root

  renovate-config-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/renovatebot/renovate:43.253.1@sha256:b39de6042de316f8504fee8a4b8c41340da485a794ca3cb26d3ab79d92e82dd5
      # github hosted runners are running as `1001:127` (ubuntu:docker)
      options: -u 1001:0 --group-add 1000 --group-add 12021 --group-add 127

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Validate Renovate configuration
        working-directory: example
        run: |
          renovate-config-validator renovate-config.js renovate-config.json
